[package]
edition = "2018"
name = "saddle-points"
version = "1.3.0"

[dependencies]
num-traits = "0.2"

[lib]
name = "saddle_points"
path = "src/lib.rs"

[[bin]]
name = "saddle_points"
path = "src/main.rs"
